name: Docker
on:
  push:
    tags:
      - v*.*.*

jobs:
  image:
    name: Image
    environment: Production
    runs-on: Ubuntu-20.04
    env:
      APPLICATION: caroline
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Authenticate to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Parse SemVer
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          context: .
          cache-from: daystram/${{ env.APPLICATION }}:latest
          build-args: |
            VERSION=v${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}
          tags: |
            daystram/${{ env.APPLICATION }}:latest
            daystram/${{ env.APPLICATION }}:${{ steps.semver.outputs.major }}
            daystram/${{ env.APPLICATION }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
            daystram/${{ env.APPLICATION }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}
